version: "3.8"
services:
    db:
        image: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
    web:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        environment:
            SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
        volumes:
            -   .:/app
            -   bundler_gems:/usr/local/bundle/
        ports:
            - "3000:3000"
        depends_on:
            - db
            - chrome
    chrome:
        image: selenium/standalone-chrome-debug
        volumes:
            - /dev/shm:/dev/shm
volumes:
    postgres:
        driver: local
    bundler_gems:
